import "./styles/cennik.css"
// import "./styles/covid.css"
import "./styles/footer.css"
import "./styles/index.css"
import "./styles/info.css"
import "./styles/kontakt.css"
import "./styles/landing.css"
import "./styles/main.css"
import "./styles/navbar.css"
// import "./styles/uslugi.css"